export const META_MASK_CONNECT_REQUEST = "META_MASK_CONNECT_REQUEST";
export const META_MASK_CONNECT_SUCCESS = "META_MASK_CONNECT_SUCCESS";
export const META_MASK_CONNECT_FAILURE = "META_MASK_CONNECT_FAILURE";

export const CONTRACT_DATA_REQUEST = "CONTRACT_DATA_REQUEST";
export const CONTRACT_DATA_SUCCESS = "CONTRACT_DATA_SUCCESS";
export const CONTRACT_DATA_FAILURE = "CONTRACT_DATA_FAILURE";

export const CONTRACT_INC_REQUEST = "CONTRACT_INC_REQUEST";
export const CONTRACT_INC_SUCCESS = "CONTRACT_INC_SUCCESS";
export const CONTRACT_INC_FAILURE = "CONTRACT_INC_FAILURE";
